# Generated by Django 5.2.4 on 2025-07-27 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_created=True,
                        auto_now_add=True,
                        verbose_name="Fecha de creación",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de modificación"
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre con el que producto será visualizado",
                        max_length=100,
                        verbose_name="Nombre del producto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción del producto",
                        null=True,
                        verbose_name="Descripción del producto",
                    ),
                ),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio del producto",
                        max_digits=10,
                        verbose_name="Precio del producto",
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        help_text="Cantidad de producto disponible",
                        verbose_name="Stock del producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuario que realizó la acción",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_auditorias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "productos",
                "managed": True,
            },
        ),
    ]
