# Generated by Django 5.2.4 on 2025-07-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomodel',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='productos/'),
        ),
    ]
